ava-labs/coreth

LICENSE
plugin/evm/block.go
plugin/evm/database.go
plugin/evm/factory.go
plugin/evm/service.go
plugin/evm/static_service.go
plugin/evm/static_service_test.go
plugin/evm/vm.go
plugin/evm/vm_genesis_parse_test.go
plugin/main.go

Pending on a PR to the gecko repo

Added the EVM as a plugin

---

plugin/evm/service.go

This fixes a fd leak caused from not closing the keystore DB.

cleaned up keystore apis

---

plugin/evm/vm.go

Enforce minimum gas price on local transactions

---

plugin/evm/block.go
plugin/evm/service.go
plugin/evm/vm.go

Switch to use eth logger

---

eth/api.go
eth/api_backend.go
eth/api_tracer.go
eth/filters/api.go
eth/filters/filter.go
internal/ethapi/api.go
plugin/evm/config.go
plugin/evm/service.go
plugin/evm/vm.go
plugin/main.go
plugin/params.go
rpc/types.go

Treat requests for Pending and Latest blocks as requests for the last Accepted block where possible
Adds JSON config to be passed in as command line arg to evm plugin
Config specifies RPC gas caps and which APIs to enable - this resolves #28 pending the corresponding change in avalanchego

Handle block number requests

---

ethclient/ethclient.go
internal/ethapi/api.go

golang json.Unmarshal appears to only decode []byte from base64 strings..
1. Parse it to a string.
2. Hex decode the string.

block extra data parse fix

---

go.mod
go.sum
plugin/evm/vm_test.go

Upgrade to avalanchego version using rpcchain definition with height

---

plugin/evm/service.go
plugin/evm/vm.go
scripts/build.sh

This PR adds the most recent git commit that coreth is compiled from into the Coreth version when it is set at compile time.

Add GitCommit into coreth version

---

plugin/evm/vm.go

This PR bumps the version to v0.4.1

Bump version to v0.4.1

---

RELEASES.md

This PR adds the release notes for v0.12.0

Add v0.12.0 release notes

---

RELEASES.md
go.mod
go.sum
plugin/evm/version.go
scripts/versions.sh

This PR bumps the version for v0.12.4

Bump to v0.12.4

---

.github/workflows/ci.yml
Dockerfile
RELEASES.md
go.mod
go.sum
gossip/bloom_test.go
plugin/evm/gossiper_atomic_gossiping_test.go
plugin/evm/mempool.go
plugin/evm/message/codec.go
plugin/evm/vm.go
scripts/versions.sh

merges master and some minor improvements

Bloom filter gossip review

---

.github/workflows/ci.yml
Dockerfile
go.mod
go.sum
peer/network_test.go
plugin/evm/vm.go
scripts/versions.sh

Bumps go version and avalanchego dependency
Updates go version and avalanchego version 
Build passses

Update to 1.10.10-rc.2

---

plugin/evm/tx_gossip_test.go

plugin/evm: rename importAccepted to more accurate txPoolNewHeads

---

plugin/evm/block.go
plugin/evm/export_tx_test.go
plugin/evm/gossip_mempool_test.go
plugin/evm/gossiper.go
plugin/evm/gossiper_atomic_gossiping_test.go
plugin/evm/mempool.go
plugin/evm/mempool_atomic_gossiping_test.go
plugin/evm/mempool_test.go
plugin/evm/service.go
plugin/evm/syncervm_test.go
plugin/evm/tx_gossip_test.go
plugin/evm/tx_test.go
plugin/evm/vm.go
plugin/evm/vm_test.go

Refactor issueTx to call issue directly on mempool

issueTx refactor

---

eth/tracers/internal/tracetest/calltrace_test.go
eth/tracers/native/call.go
eth/tracers/native/prestate.go

This PR migrates https://github.com/ethereum/go-ethereum/pull/27691/files and addresses https://github.com/ava-labs/coreth/issues/369

eth/tracers/native: migrate panic on memory read in prestate tracer

---

peer/client.go
peer/network.go
peer/network_test.go
peer/waiting_handler.go
sync/client/client.go
sync/client/mock_network.go

Ported changes from Subnet-EVM PR: https://github.com/ava-labs/subnet-evm/pull/874

add context to network handlers

---

core/blockchain.go
core/state/trie_prefetcher.go
eth/ethconfig/config.go
plugin/evm/config.go

[core/state] Prefetch Tries Concurrently (Aggressive=16)

---

core/state/trie_prefetcher.go

[core/state] Prefetch Tries Concurrently (Aggressive=48)

---

core/state/trie_prefetcher.go
utils/bounded_workers.go

[core/state] Prefetch Trie Nits

---

peer/client.go
peer/waiting_handler.go

Adds a helper method to remove duplicated code.

add WaitForResult

---

params/config.go

Ports https://github.com/ava-labs/subnet-evm/pull/1016

show strings in pointers

---

go.mod
go.sum
peer/network.go
peer/network_test.go
plugin/evm/syncervm_test.go
plugin/evm/tx_gossip_test.go
plugin/evm/vm.go
scripts/versions.sh

See https://github.com/ava-labs/avalanchego/pull/2452
Updates to new SDK API
UTs

Update to new SDK API

---

accounts/abi/topics.go
accounts/abi/topics_test.go

Mirror https://github.com/ava-labs/subnet-evm/pull/1045

fix negative bigint topics

---

eth/state_accessor.go
eth/tracers/api_test.go

Mirrors https://github.com/ava-labs/subnet-evm/pull/1046

pass configs to StateAtBlock

---

plugin/evm/gossip_test.go

The test previously flaked on windows. Hopefully this better handles the slow tests case (increases timeout from 1s to 10s) while also speeding up the test is the normal case (this reduced the time it took to execute on my local machine by the full 1s).
Also, the bloom filter is not safe to access while resetting... Which previously could have happened (in the test). The test now correctly grabs the lock to avoid racy behavior.
`time.Sleep` -> `require.Eventually`
add `RLock() + defer RUnlock()`

Fix racy bloom access and replace time.Sleep with require.Eventually

---

accounts/abi/bind/backends/simulated.go
internal/ethapi/api.go
internal/ethapi/transaction_args.go
plugin/evm/message/cross_chain_handler.go
plugin/evm/syncervm_client.go
sync/handlers/code_request.go

We intentionally updated these log levels in subnet-evm, so we should update them in coreth by the same logic presented here: https://github.com/ava-labs/subnet-evm/pull/609
Applies changes from the referenced PR where applicable
CI

Update log levels

---

warp/aggregator/signature_getter.go
warp/backend.go

Mirror of https://github.com/ava-labs/subnet-evm/pull/1068

Add error handling to Warp (#1068)

---

.github/workflows/ci.yml
Dockerfile
accounts/abi/bind/bind_test.go
go.mod
go.sum
plugin/evm/atomic_trie_repair_test.go
plugin/evm/import_tx.go
scripts/versions.sh
sync/handlers/leafs_request.go

Counterpart to https://github.com/ava-labs/avalanchego/pull/2710
Update :)
CI

Update minimum golang version to v1.21.7

---

plugin/evm/tx_gossip_test.go

fixes the race by shutting down the vms

Gossip cleanup test race

---

go.mod
go.sum
peer/network_test.go
plugin/evm/config.go
plugin/evm/gossiper_atomic_gossiping_test.go
plugin/evm/gossiper_eth_gossiping_test.go
plugin/evm/syncervm_test.go
plugin/evm/vm.go
plugin/evm/vm_test.go
scripts/versions.sh

Corresponding PR to: https://github.com/ava-labs/avalanchego/pull/2785

Update app gossip params

---

RELEASES.md
go.mod
go.sum
plugin/evm/version.go
scripts/versions.sh

Bumps versions for v0.13.1 release

bump versions for v0.13.1

---

peer/network.go

See: https://github.com/ava-labs/subnet-evm/pull/1142

Remove cancellation for Send.*AppRequest messages

---

core/txpool/legacypool/legacypool.go
core/txpool/legacypool/legacypool_test.go

mirror of https://github.com/ava-labs/subnet-evm/pull/1159

fix local flag in legacypool

---

.github/workflows/ci.yml
core/blockchain.go
core/blockchain_test.go
core/test_blockchain.go
eth/backend.go
eth/chain_with_final_block.go
metrics/opentsdb_test.go
plugin/evm/atomic_syncer_test.go
plugin/evm/atomic_trie_repair_test.go
plugin/evm/block.go
plugin/evm/gossip.go
plugin/evm/gossip_test.go
plugin/evm/syncervm_test.go
plugin/evm/vm.go
scripts/build_test.sh
scripts/lint.sh

Adds matrix to tests and use race for all UTs

add matrix and race to UTs

---

eth/backend.go
eth/chain_with_final_block.go

Disabled unused blobpool
Comments out related part of the code

disable blobpool

---

RELEASES.md
plugin/evm/version.go

start v0.13.4 release cycle w/ initial notes

---

core/state/snapshot/snapshot.go

improve abortGeneration locks

---

RELEASES.md
go.mod
go.sum
scripts/versions.sh

Updates release notes and avalanchego version

bump verions, notes for v0.13.4 release

---

log/handler.go

fix log ingestion in Datadog

---

ethclient/corethclient/corethclient.go
ethclient/ethclient.go
interfaces/interfaces.go

mirrors https://github.com/ava-labs/subnet-evm/commit/caa42de94a0f490e8aba3cddf7ac57312336c472

add missing fields to "toCallArg" (#1197)

---

sync/statesync/state_syncer.go

Same as https://github.com/ava-labs/subnet-evm/pull/1201

resolve race in closing sync segments channel

---

.github/workflows/ci.yml
Dockerfile
RELEASES.md
go.mod
go.sum
plugin/evm/atomic_trie_test.go
plugin/evm/version.go
scripts/versions.sh

Prepare the v0.13.5 release to follow avalanchego 1.11.7

prepare v0.13.5 release

---

plugin/evm/atomic_syncer_test.go
plugin/evm/atomic_trie_iterator_test.go
plugin/evm/atomic_trie_test.go
plugin/evm/atomic_tx_repository.go
plugin/evm/atomic_tx_repository_test.go
plugin/evm/vm.go

atomic_repository: remove unused arg

---

rpc/handler.go

Mirror of https://github.com/ava-labs/subnet-evm/pull/1225

rpc: truncate call error data logs (#30028)

---

go.mod
go.sum
scripts/versions.sh

Bumps avalanchego to v1.11.10-rc.0

bump avalanchego to v1.11.10-rc.0

---

RELEASES.md
plugin/evm/version.go

release v0.13.7

---

params/avalanche_params.go
params/config.go
params/config_extra.go
plugin/evm/vm.go
plugin/evm/vm_test.go

Better comments and some minor refactoring

nits, update comments

---

.github/workflows/sync-subnet-evm-branch.yml

Just adding a workflow so I can iterate

gh actions: add skeleton for sync-subnet-evm-branch

---

core/blockchain.go
core/blockchain_test.go
core/txindexer_test.go
eth/backend.go
eth/ethconfig/config.go
plugin/evm/config_test.go
plugin/evm/syncervm_test.go
plugin/evm/tx_gossip_test.go
plugin/evm/vm.go

Coreth geth v1.13.14 sync rw

---

consensus/dummy/dynamic_fees.go

Remove extra var to improve readability

improve readability by removing extra var

---

consensus/dummy/dynamic_fees.go
consensus/dummy/dynamic_fees_test.go

Fixes modified common.Big1
Failing regression UT: https://github.com/ava-labs/coreth/actions/runs/10891616469/job/30222904746?pr=649

fix modifying common.Big1

---

miner/worker.go

Mirror PR: https://github.com/ava-labs/subnet-evm/pull/1358

track env size

---

.github/workflows/ci.yml
.github/workflows/sync-subnet-evm-branch.yml
Dockerfile
accounts/abi/bind/bind_test.go
go.mod
go.sum
peer/network.go
peer/stats/stats.go
scripts/versions.sh

Syncs Subnet-EVM up to e93eb1e7fd4948049282eab22137899fe9e6617b

Sync subnet evm

---

core/state/prefetcher_database.go
core/state/trie_prefetcher.go

this change introduces a new type for the PrefetcherTrie and PrefetcherDB, making behaviors such as Close and wrapping the prefetcher tree more explicit.
Note we could merge NewPrefetcherTrie into OpenTrie and OpenStorageTrie as they would be needed for a pass-through anyway.
IMO this level of changes to the upstream code is acceptable but I found changing the type of CopyTrie can lead to lots of modifications, so I suggest we leave it be.

trie_prefetcher: alternate structure (possible improvements)

---

README.md

chore: changed the link to the documentation

---

core/test_blockchain.go

Seems this test was accidentally removed during a merge.
Restores the test (making needed modifications)
CI
N/A
N/A

restore TestReorgReInsert

---

precompile/contracts/warp/README.md

ps: updating this file is important cause we it as a remote content source in the docs.

update: readme changes for 9000 upgrade 

---

consensus/dummy/dynamic_fees.go
go.mod
go.sum
params/avalanche_params.go
plugin/evm/ap5/params.go
plugin/evm/atomic/export_tx.go
plugin/evm/atomic/import_tx.go
plugin/evm/block_verification.go
plugin/evm/header/block_gas_cost.go
plugin/evm/header/block_gas_cost_test.go
plugin/evm/vm.go
plugin/evm/vm_warp_test.go
precompile/contracts/warp/predicate_test.go
precompile/contracts/warp/signature_verification_test.go
scripts/versions.sh
utils/numbers.go
utils/numbers_test.go
warp/aggregator/aggregator_test.go

Merges master upto 6a9db20 which includes an avalanchego dependency update
Avalanchego Dependency PR: https://github.com/ava-labs/avalanchego/pull/3730

Merge master 6a9db20

---

plugin/evm/atomic/tx.go

I personally find this code much more clear, but if people disagree (or now isn't the right time) we can close this.
Code cleanup
existing CI
No.
No.

Cleanup `atomic.CalculateDynamicFee`

---

.github/workflows/ci.yml
.github/workflows/sync-subnet-evm-branch.yml

Updates deprecated ubuntu 20.04 version to 22.04

Remove usage of ubuntu-20.04

---

plugin/evm/vm.go

Improved inspection of instance logs.
Additional log attribute.
NA
No
No

chore: log libevm version during VM init

---

core/genesis.go

I want to check this error since I spent some time debugging yesterday and this would have made it obvious.

nit: check genesis commit error

---

scripts/known_flakes.txt

seems flakey
https://github.com/ava-labs/coreth/actions/runs/14091482068/job/39469000515?pr=894

add flake: TestUpdatedKeyfileContents

---

plugin/evm/vm.go
plugin/evm/vm_test.go

During the testing refactor, I ran into a few "odd" tests. This cleans them up.
Simplify tests that are needlessly complex.
CI
No
No

Simplify weird VM tests

---

plugin/evm/block_builder.go
plugin/evm/customethclient/ethclient_ext.go
plugin/evm/vm.go
plugin/evm/vm_warp_test.go

Remove dead code

---

plugin/evm/api.md

updated link evm api

---

eth/ethconfig/config.md

switch https://build.avax.network/docs/nodes/chain-configs/c-chain to being remotely fetched from this repo.
No
No

feat: c-chain config markdown

---

RELEASES.md

updates releases md with v0.15.1

cut v0.15.1 in release.md

---

sync/statesync/sync_test.go

These tests were overly verbose when our style guide recommends using `require` if possible.
Replaces all checks to use `require` instead of `assert` or `t.Fatalf`.
Existing UT
No
No

style: use require in statesync tests

---

plugin/evm/atomic/vm/vm.go
plugin/evm/atomic/vm/vm_test.go

This code isn't used since we removed the keystore.
Delete.
CI
No
No

Remove dead code for creating atomic txs

---

plugin/evm/atomic/vm/vm_test.go

Minor cleanup / deadcode removal.
trivial.
CI
No
No

Cleanup keystore creation

---

plugin/evm/upgrade/acp176/acp176.go

Corrects the math in the comment explaining `TargetToPriceUpdateConversion`
N/A
N/A
No
No

Correct TargetToPriceUpdateConversion comment
