ava-labs/coreth

- plugin/evm/vm.go
The IP filter was added to prevent calls from non-localhost, but gecko has its own access controls: including a flag to control the interface to bind to which defaults to the local interface, and soon an access token system.
@Determinant has confirmed that this is okay to remove given that the API is only available on the local interface by default already.
> Remove IP filter

- plugin/evm/vm.go
Fixes #16 at base level. Previous PR #17 to fix it prevented invalid transactions from being added to the tx pool, but did not address problem of failing to build a block causing the chain to lock up and block forever on newBlockChan
> Add nil to newBlockChan if block verification errors

- internal/ethapi/api.go
Adjusts the eth_getBlockByNumber to include 'blockExtraData'...
Exposes [evm atomicTx](https://github.com/ava-labs/coreth/blob/ae4541f42a666fb5ae1c36d6f7423c3d9eb2c875/plugin/evm/vm.go#L188)
`curl -X POST --data "{\"id\":0,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"latest\",false]}"  -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/C/rpc`
`{"jsonrpc":"2.0","id":0,"result":{"blockExtraData":"0x000000000000000000057f....","difficulty":"0x1","extraData":"0xd98301...","gasLimit":"0x2dbdfc6","gasUsed":"0x0","hash":"0x550165eb6e539a7c17fbd8f5624655ad7e4ff34d749a683f55b6063906890e46","logsBloom":"0x0000...","miner":"0x0100000000000000000000000000000000000000","mixHash":"0x00...","nonce":"0x0000000000000000","number":"0x2f0","parentHash":"0xca4a1ac1c043af92ca1b9 …
> add block extra data to eth_getBlockByNumber

- core/blockchain.go
- core/tx_pool.go
- coreth.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
Adds a regression test that catches the case where the consensus engine calls SetPreference on a block that may not become finalized resulting in the corruption of eth's notion of the canonical chain. Note: this is different from the canonical chain maintained by the VM, so it results in invalid responses from the API, but does not impact anything on-chain.
> Add regression test for set preference race

- core/blockchain.go
- core/tx_pool.go
- coreth.go
- miner/miner.go
- miner/worker.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
This PR alters the `vm` logic to only `SetTail` when a block has been accepted. To avoid creating additional contention on block production, this PR alters the `miner` to build off of the last preferred block (instead of the last block we called `SetTail` on).
> Only `SetTail` for Accepted Blocks

- core/vm/interpreter.go
- eth/tracers/tracer.go
Related: https://github.com/ava-labs/avalanchego/issues/752
`debug_traceTransaction` will panic when tracing transactions (with this [script](https://github.com/poanetwork/blockscout/blob/master/apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js)) that deploy contracts with no code. This was discovered when tracing `0xc0f33007b76c2d8675cdc34e979b94f3aab4778572be0b185115bbd4686f6a17` on `FUJI`.
The root cause of this issue is that the `dbWrapper.db` is not populated in the tracer when a transaction contains a lone contract deployment that has no code. `result` (called at the end of `debug_traceTransaction` assumes this wrapper was populated with `StateDB` at some point.
> [Tracer] Handle Empty Contract Deployments

- coreth.go
- eth/backend.go
- eth/filters/api.go
- examples/block/main.go
- examples/chain/main.go
- examples/counter/main.go
- examples/multicoin/main.go
- examples/payments/main.go
- plugin/evm/config.go
- plugin/evm/vm.go
- plugin/params.go
This PR creates an optional cap to set on the max number of blocks a GetLogs request will attempt to fetch.
> Add optional config for max blocks per getLogs request

- plugin/evm/vm.go
Make `net_version` call return the correct network ID.
> fix:evm.VM: use ChainID from the genesis block

- params/config.go
This PR adds the Cortina Fuji activation timestamp for April 6, 2023 15:00 UTC.
Adds the new timestamp into `params/config.go`
CI / no additional testing for adding timestamp activation.
> Add Cortina activation timestamp for April 6

- .github/workflows/ci.yml
- go.mod
- go.sum
- plugin/evm/version.go
- scripts/versions.sh
This PR bumps the version to v0.12.0 and bumps the AvalancheGo dependency to v1.9.16
CI
> Bump version to v0.12.0 and bump ago dep to v1.9.16

- plugin/evm/atomic_tx_repository.go
- plugin/evm/atomic_tx_repository_test.go
- plugin/evm/tx.go
- plugin/evm/vm_test.go
`slices.Sort` is faster.  I only touched files in `plugin` to minimize the diff with geth.
Replace `sort.` with `slices.` methods
Existing UT
> Use `slices` methods instead of `sort` methods

- plugin/evm/export_tx.go
- plugin/evm/export_tx_test.go
- plugin/evm/import_tx.go
- plugin/evm/import_tx_test.go
- plugin/evm/tx.go
- plugin/evm/tx_test.go
- plugin/evm/vm.go
So it can be used downstream
`c` --> `C`
N/A
> export CalculateDynamicFee

- core/rawdb/accessors_state_sync.go
- core/rawdb/accessors_state_sync_test.go
- core/rawdb/database.go
Since trie nodes are not stored with a prefix, it is dangerous to call ClearPrefix without restricting the length.
As the only code path that calls this without a long enough prefix is clearIfRootDoesNotMatch this does not
represent a serious problem.
It is possible this may have corrupted trie nodes if:
- the user state sync'ed and interrupted that sync
- waited >= 300,000 blocks
- tried to state sync again
- and they had a previously populated DB,
- and trie nodes were prefixed with `sync_storage` or `sync_segments`.
Adds the expected key length as a parameter to the ClearPrefix function so the caller does not accidentally
erase trie nodes.
UTs
> Restrict ClearPrefix by key size

- core/blockchain.go
- plugin/evm/vm_test.go
This PR fixes a regression introduced in v0.12.3 where `collectUnflattenedLogs` returns nil for a block that contains no transactions, which causes `nil` to be returned from `core/blockchain.go` and this is treated as an error in the filter system code here: https://github.com/ava-labs/coreth/blob/v0.12.3/eth/filters/filter_system.go#L117.
This has caused a request for `eth_getLogs` to return an error for blocks that only contain an atomic transaction.
This patches the bug by ensuring that the `logs` slice is initialized to a non-empty value instead of only appending to it inside of the for loop, which is never hit if there are no logs.
Add to existing unit test for atomic transactions in the VM. This is the simplest place to add the test. We cannot add it in the core package because it …
> Fix collect unflattened logs

- .github/workflows/ci.yml
- Dockerfile
For consistency we should use the same go version across ci and release
Changes 1.20 -> 1.19
CI
> Use go1.19 in CI for consistency with avalanchego

- core/blockchain_log_test.go
This PR cleans up the existing accepted log subscription unit test by renaming it and moving variables only relevant to this test inside of the relevant test.
Just cleanup
Run modified test locally + CI
> Cleanup accepted logs subscription test

- RELEASES.md
- go.mod
- go.sum
- plugin/evm/version.go
This PR creates a new section in the release notes for v0.12.5, bumps the reported version to v0.12.5, and bumps the AvalancheGo dependency to the latest release v1.10.5.
n/a
CI
> Bump coreth to v0.12.5 and bump avalanchego dep to v1.10.5

- RELEASES.md
- go.mod
- go.sum
- plugin/evm/vm.go
- scripts/versions.sh
This PR bumps AvalancheGo dependency to use v1.10.6-rc.4 and updates the cache sizes used by the chain state cache to use the new sized LRU cache to limit the total memory allocated to the cache based off of bytes size (limited to a total of 20MB) as opposed to a specific number of blocks.
Since AvalancheGo imports Coreth, it will replace the version of AvalancheGo imported by Coreth with the actual current code when it's compiled. As a result, since AvalancheGo has switched to inputting sizes based off of the total memory taken up by these caches instead of the number of elements, we need to update the sizes for the AvalancheGo release.
Otherwise, the chain state cache will go from allocating 100/50/50 elements to the respective caches to allocating that number of bytes to each of those …
> Bump avalanchego to v1.10.6-rc.4

- sync/README.md
> Fix typo in sync/README.md

- plugin/evm/config.go
- plugin/evm/gossiper.go
- plugin/evm/vm.go
We have different flag names in Subnet-EVM as [here](https://github.com/ava-labs/subnet-evm/blob/master/plugin/evm/config.go#L157-L159).  Renamed those to be same with Subnet-EVM.
Also added a deprecation function which would set new configs to old ones if old ones has non-default values, and emits a warn log.
> renamed flags

- go.mod
- go.sum
- plugin/evm/vm.go
AvalancheGo is removing the `block.HeightIndexedChainVM` interface.
Updates the avalanchego dependency and removes the type assertion.
CI
> Update avalanchego dependency to v1.10.9-rc.4

- rpc/client_test.go
Test is present in upstream: https://github.com/ethereum/go-ethereum/blob/v1.12.0/rpc/client_test.go#L172
Copies the test
CI
> add upstream test: TestClientBatchRequest_len

- .github/workflows/ci.yml
- scripts/versions.sh
Also bump targeted version of avalanchego to the v1.10.8 (which also uses golang 1.19.12).
> Bump golang version to 1.19.12 for CI

- core/state/snapshot/snapshot.go
This PR migrates https://github.com/ethereum/go-ethereum/pull/27977.
This increases the cap on the size of a batch when flattening a snapshot diff layer to disk. This is a non-atomic operation to ensure that flattening does not create such a large batch that it causes an OOM.
However, breaking this up may result in invalidating the snapshot since you may apply only part of the change, which results in needing to re-generate the snapshot.
Increasing the capped size to 64MB provides a reasonable cap to avoid an OOM and drastically increases the size of a diff that is needed to potentially corrupt a snapshot.
> core/state/snapshot: increase batch size during diffToDisk

- .github/workflows/ci.yml
- .gitignore
- scripts/tests.e2e.sh
Adds a CI job to run the pinned version of the avalanchego e2e tests against the latest version of coreth. Once the PRs for #1547 are merged to avalanchego to ensure equivalent coverage to the current kurtosis e2e, the current coreth kurtosis e2e job can be disabled.
A new script in the coreth repo - `./scripts/tests.e2e.sh`:
- checks out the target version of AvalancheGo
- configures it to use the local working directory as its coreth dependency
- builds avalanchego binary
- runs the AvalancheGo e2e test script
Checked that the new `AvalancheGo E2E Tests` job exists and is passing.
> e2e: Add avalanchego e2e job

- peer/network.go
- peer/network_test.go
- plugin/evm/vm.go
Adds the P2P SDK's router to handle incoming sdk messages
Forwards messages that fail unmarshaling against the codec into the SDK router
Added a unit test
> Add SDK Router message handling

- peer/network.go
- peer/network_test.go
We forget to release the requests semaphore after shutting down the p2p layer
Adds a release if we drop an outbound request
Added a regression test
> Fix hanging requests after Shutdown

- plugin/evm/syncervm_test.go
- Fixes a flake in TestVMShutdownWhileSyncing
- Cleans up some test code
- Adds additional error checking
- Removes unneeded goroutine in AppSend (still needed for responses)
Re-opens the "chaindb" since it may be closed in the vm.Shutdown()
Alternatively we could remove the check for synced heights in case the sync errors. Either is fine by me.
CI, running multiple times locally
> Fix TestVMShutdownWhileSyncing

- go.mod
- go.sum
- plugin/evm/vm.go
- scripts/versions.sh
Drops outbound requests for gossip
updates to new gossip package
This is tested in the upstream tests
> Drop outbound gossip requests for non-validators

- core/vm/instructions.go
This PR adds a de-activation comment to the `opCallExpert` code to make it clear this code was de-activated in ApricotPhase2.
> core/vm: add de-activation of opCallExpert comment

- go.mod
- go.sum
- scripts/tests.e2e.sh
- scripts/versions.sh
- Running all avalanchego tests increases the possibility of failing coreth CI on codepaths that don't involve coreth. Running only tests that exercise the C-Chain reduces the scope of that potential failure.
- Update to avalanchego v1.10.11 which supports restricting e2e execution to just C-Chain tests.
- Passes ginkgo flags to the avalanchego tests to restrict test execution to tests using the C-Chain 
- CI
> e2e: Run only C-Chain tests

- .github/CONTRIBUTING.md
Changes were made because some golang.org links died.
Clicking on the links started to go to the go.dev site.
Clicking on the old links used to take you to the new ones, now you will click on the new ones.
> Fixed some go.dev links.

- .github/workflows/ci.yml
Bump golangci version to latest
Similar to https://github.com/ava-labs/subnet-evm/pull/927/files
N/A
> bump golangci-lint

- params/config.go
This PR adds a comment enumerating the changes included in the DUpgrade. The scheduled changes include the activation of the EIPs from the [Shanghai Upgrade](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md#included-eips) and [Avalanche Warp Messaging](https://github.com/ava-labs/subnet-evm/blob/v0.5.6/x/warp/README.md).
The Shanghai Upgrade includes EIPs:
- EIP-3651 (Warm Coinbase)
- EIP3855 (PUSH0)
- EIP-3860 (Limit and meter initcode)
- EIP-4895 (Beacon chain push withdrawls as operations, ignored since it is not relevant here)
- EIP-6049 (Deprecate SELFDESTRUCT, this is an official deprecation notice and not a change in behavior)
> params: enumerate changes in DUpgrade including Shanghai upgrade

- go.mod
- go.sum
- plugin/evm/admin.go
- plugin/evm/service.go
- plugin/evm/vm.go
- scripts/versions.sh
See: [#2148](https://github.com/ava-labs/avalanchego/pull/2148)
Explicitly grabs the context lock where it would have implicitly been grabbed before. There were a _couple_ APIs that I felt obviously didn't require a lock. But this should be a ~noop change.
CI
> Remove lock options from http handlers

- scripts/tests.e2e.sh
I don't see another way to do this except doing a full clone instead of the previous single branch clone.
> Update e2e test script to support hash pins

- .github/workflows/ci.yml
Saving the network data produced by the e2e test is essential to diagnosing CI failures.
> e2e: Save network data as artifact

- plugin/evm/atomic_syncer_test.go
- sync/client/client_test.go
- sync/handlers/leafs_request_test.go
- sync/statesync/sync_test.go
- sync/statesync/test_sync.go
- sync/syncutils/test_trie.go
- trie/triedb/hashdb/database.go
Reduces diff with upstream
Moves code around and makes no-op changes.
CI
> move trie generation helper out of trie/

- go.mod
- go.sum
- plugin/evm/syncervm_test.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- scripts/versions.sh
Accommodates removal of `database.Manager` in [this](https://github.com/ava-labs/avalanchego/pull/2239) avalanchego PR. 
Remove `database.Manager`; update avalanchego version.
Existing UT.
> Remove db manager

- RELEASES.md
- go.mod
- go.sum
- plugin/evm/version.go
- scripts/versions.sh
- Start the release cycle for v0.12.8
- Update AvalancheGo to v1.10.15
- Update RELEASES.md
> Start v0.12.8 release

- params/config.go
- Fixes typos resulting in incorrectly displayed Cancun time in chain info text.
- Fixes returned error in case of Cancun timestamp compatibility to refer to the Cancun timestamp
Fixes typos
CI
> params: fix log + errors for Cancun timestamp

- plugin/evm/vm.go
There is an extra err nil check for `vm.newBlock()`. We can remove this
> remove extra err check

- ethclient/ethclient.go
- rpc/types.go
Aligns rpc/types.go more with upstream by adding SafeBlock as a constant and permitting the blockNr -4 to map to it.
Behaviorally, we continue to use lastAccepted block for valid negative block numbers and this change modifies IsAccepted to account for this.
As described above
CI
> align rpc/types.go with upstream

- sync/README.md
> docs: fix typo

- core/blockchain.go
This PR moves updating the `acceptorTip` to before sending events to any subscribers. This ensures that any client that relies on these events will observe that any subsequent request observes a state consistent with the transactions/block being marked as accepted.
CI
> Update acceptor tip before sending chain events to subscribers

- plugin/evm/message/codec.go
- sync/handlers/block_request.go
This PR adds a soft cap while constructing a response to `BlockRequests` during state sync.
The soft cap is enforced while constructing the response, to ensure that we do not hit the max message size while using the network codec to marshal the overall response.
> sync/handlers: add soft cap on total block data size while serving block requests

- plugin/evm/atomic_syncer.go
- plugin/evm/atomic_syncer_test.go
Existing logic is querying the atomic trie for the last committed, then using that to determine whether or not new keys received in syncing should create a new commit.
This results in incorrect metadata (height --> root mapping) to be stored, as when a key with height > lastCommitted is received, it can create an additional commit at the previous height.
Maintains the lastHeight the syncer has fully added to the trie.
CI, regression test
> Fix overwriting of atomic trie roots

- plugin/evm/atomic_backend.go
- plugin/evm/atomic_syncer.go
- plugin/evm/atomic_syncer_test.go
plugin/evm code should honor the invariant specified for committing tries here:
https://github.com/ava-labs/coreth/blob/0eef20a5aca777b5177961bc349fdb0da99c2d6a/trie/trie.go#L41-L48
Re-opens the trie from the database after commit.
CI
> Fix trie reuse after Commit in atomic sync

- plugin/evm/message/codec.go
- plugin/evm/message/message_test.go
- sync/client/client.go
- sync/handlers/block_request_test.go
Initializing the codec as such:
https://github.com/ava-labs/coreth/blame/abde8d63c32d75b8e966e41eabea0051a2ffa50d/plugin/evm/message/codec.go#L24-L25
does not result in the codec's max slice marshal capacity increasing (see https://github.com/ava-labs/avalanchego/blob/master/codec/linearcodec/codec.go#L55-L65)
Fixes https://github.com/ava-labs/avalanchego/issues/2454
Also this reduces the log level for retrying failed messages from peers to Debug so invalid responses cannot cause syncing clients to log @ info.
Calls `NewCustomMaxLength`.
Fixes the UT to encode a large block
> Fix codec size for large blocks

- precompile/contracts/warp/contract.go
This PR updates the `SendWarpMessageGasCost` to `3*params.LogTopicGas` to reflect that there are now three topics emitted (instead of 4 previous to https://github.com/ava-labs/subnet-evm/pull/923/files)
> Update warp log gas cost to reflect num topics

- go.mod
- go.sum
- plugin/evm/gossip.go
- plugin/evm/mempool.go
- plugin/evm/tx_gossip_test.go
- scripts/versions.sh
See: https://github.com/ava-labs/avalanchego/pull/2547
Updates the avalanchego version.
> Update avalanchego dependency to v1.10.18-rc.8

- go.mod
- go.sum
Use same version as latest upstream
Changes go.mod / go.sum
CI
> bump gnark dependencies

- plugin/evm/gossip.go
Embedding the no-op handler could result into unexpected behavior in case interface changes and no-op handler implementation changes. IMO it's better to depend on the interface type check and introduce breaking change rather than using a no-op implementation
Removes embedded no-op handler and implements interface functions.
UTs should cover this.
> remove no-op handler

- core/predicate_check.go
- core/predicate_check_test.go
- precompile/contracts/warp/config.go
- precompile/contracts/warp/predicate_test.go
- precompile/precompileconfig/config.go
- precompile/precompileconfig/mocks.go
- precompile/testutils/test_predicate.go
Mirrors: https://github.com/ava-labs/subnet-evm/pull/960
> verify single predicate (#960)

- eth/gasprice/gasprice.go
- go.mod
- go.sum
- scripts/versions.sh
Reverts ava-labs/coreth#433
We aren't ready to merge the avalanchego side of this PR, so we should revert this change until after the next release.
> Revert "Use int64 timestamp"

- go.mod
- go.sum
- plugin/evm/gossip.go
- plugin/evm/mempool.go
- plugin/evm/tx_gossip_test.go
- plugin/evm/vm.go
- scripts/versions.sh
Rationale: https://github.com/ava-labs/avalanchego/pull/2591
Modifies reset logic to grow the bloom filter if the number of target items grows.
CI + Load Test
> [utils/bloom] Dynamic Bloom Filter

- go.mod
- go.sum
- plugin/evm/gossip.go
- plugin/evm/gossip_test.go
- plugin/evm/mempool.go
- plugin/evm/mempool_test.go
- plugin/evm/tx_gossip_test.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- scripts/tests.e2e.sh
- scripts/versions.sh
Bumps AvalancheGo and adds bloom filter metrics. 
Closes: #454 
Passes registerer and namespace as input to new bloom filter functions.  
Existing and AvalancheGo UTs should cover this.
> add bloom filter metrics

- plugin/evm/gossip.go
- plugin/evm/gossip_test.go
- plugin/evm/gossiper_eth_gossiping_test.go
There is a bug that prevents pending txs to be added to bloom filter after reset.
Change variables from pendingTxs to iterated txs 
Added UT
No need
> Bloom filter reset

- warp/client.go
- warp/service.go
Exposes `GetMessage` in the Warp API. The use case is for clients (such as awm-relayer) to fetch a Warp message while only needing to know the ID, not the full message bytes.
Corresponding subnet-evm PR: https://github.com/ava-labs/subnet-evm/pull/1062
Adds `GetMessage` to client.go and service.go
Manually tested via the client in a local deployment
N/A
> Expose GetMessage in Warp API

- go.mod
- go.sum
- params/config.go
- scripts/versions.sh
1. Hardcoding the same timestamp twice is error prone and annoying.
2. This allows easier fork testing because only the avalanchego timestamps need to be modified to test upgrades locally
- Depends on avalanchego's `version` package for timestamps.
- This does change the timestamp for `Durango` from `nil` to the year `10000`. This should be safe because modifications of the fork times are safe as long as the fork hasn't been activated on chain yet.
> Use avalanchego upgrade times

- accounts/abi/bind/bind_test.go
Does not seem this is necessary for the tests to pass, since this is both different in subnet-evm and is not present in upstream, I suggest we remove it.
Removes setting auth.GasFeeCap
CI + running test several times locally
> bind_test: remove auth.GasFeeCap

- params/avalanche_params.go
- plugin/evm/message/leafs_request.go
- sync/handlers/code_request.go
- sync/statesync/code_syncer.go
Moves the definition of MaxCodeHashesPerRequest from params to `evm.message`, to the same place it's defined in subnet-evm.
We could move it to `code_request.go` instead in both repos
Moves a constant
CI
> move MaxCodeHashesPerRequest

- core/txpool/txpool.go
- miner/worker.go
This change allows transactions that have used a base fee that is less than the last fee update's estimate but greater than the actual built block's fee to be included in the block.
This is particularly useful when the base fee is decreasing (with time) and the client is using an estimate that is based on the current time, but the periodic update has not taken effect yet.
Sets the value used to filter txs before filtering them
CI
> Update TxPool base fee prior to filtering txs based on effective tip

- precompile/contracts/warp/README.md
We should add this page to the AWM section of the docs. Some of the links were pointing to older versions of the coreth repo so i fixed that too.  
edited `precompile/contracts/warp/README.md`
[Docs PR](https://github.com/ava-labs/avalanche-docs/pull/1646)
View here: https://meag-awm-evm-integration.avalanche-docs.pages.dev/build/cross-chain/awm/evm-integration
> Format for docs integration

- RELEASES.md
- go.mod
- go.sum
- peer/network_test.go
- plugin/evm/version.go
- scripts/versions.sh
> update avago to v1.11.0

- core/txpool/txpool.go
- core/txpool/txpool_test.go
- eth/backend.go
- plugin/evm/config.go
- plugin/evm/config_test.go
- plugin/evm/gossip_test.go
- plugin/evm/vm.go
Currently the txpool journal is disabled by explicitly setting `Journal = ""` in the `eth/backend`. This is fairly odd - as we explicitly support users to configure the `Journal`.
- Removes the `Journal` config options and sets the default value to be disabled.
- Adds a comment that we should ensure that local transactions are gossiped if we re-enable journaling.
> Remove unused journaling configs

- go.mod
- go.sum
- plugin/evm/config.go
- plugin/evm/vm.go
- scripts/versions.sh
See: https://github.com/ava-labs/avalanchego/pull/2787
> Increase gossip size on first push

- precompile/contracts/warp/config.go
During bootstrapping, this log is spammed to the console. This change aligns the log level to other logs that are hit during normal execution.
`Info` -> `Debug`
N/A
> Lower warp log level

- core/txpool/txpool.go
- plugin/evm/config.go
- plugin/evm/vm.go
Currently the `txpool.Lifetime` is hardcoded to `3h`. This makes it configurable and defaults to `10m`.
Add to config + update default.
> Add tx-pool-lifetime config (10m)

- go.mod
- go.sum
- peer/network_test.go
- plugin/evm/config.go
- plugin/evm/gossiper_atomic_gossiping_test.go
- plugin/evm/gossiper_eth_gossiping_test.go
- plugin/evm/syncervm_test.go
- plugin/evm/tx_gossip_test.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- scripts/versions.sh
- warp/aggregator/aggregator_test.go
See: https://github.com/ava-labs/avalanchego/pull/2835
> Integrate stake weighted gossip selection

- plugin/evm/atomic_syncer_test.go
- sync/syncutils/test_trie.go
Other tests that run concurrently may violate the test's assumption that it can reproduce the trie keys by setting the random seed.
Creates the larger tree by expanding on the first tree, by making some functions more general.
CI
> avoid relying on rand.Seed for deterministic results

- plugin/evm/service.go
https://github.com/ava-labs/avalanchego/issues/2853
Since chain state updates run asynchronously with VM block acceptance,
avoid returning [Accepted] until the chain state reaches the block
containing the atomic tx.
CI
> Wait for chain state updates to report atomic tx as Accepted

- .github/workflows/ci.yml
- Dockerfile
- RELEASES.md
- go.mod
- plugin/evm/version.go
- scripts/build.sh
Updates the version string and golang versions in preparations for an RC
updates versions
CI
> bump version to v0.13.3 & go 1.21.9

- RELEASES.md
- peer/network.go
See: https://github.com/ava-labs/avalanchego/pull/2981
> Mark ourself as connected

- plugin/evm/syncervm_client.go
- plugin/evm/vm.go
> state sync: initialize snapshots in bootstrap set mode

- params/config.go
Changes string so times align in logs / on screen
> nit: fix spacing in config printout for Durango

- sync/statesync/trie_sync_stats.go
- sync/statesync/trie_sync_stats_test.go
Currently the ETA calculation produces an intermediate value that can overflow `int64`, which causes the calculation to be incorrect (and even can produce negative numbers).
Uses avalanchego's ETA calculation.
> fix state sync eta overflow

- go.mod
- go.sum
- plugin/evm/vm.go
- scripts/versions.sh
- utils/snow.go
Avalanchego is no longer supporting the `metrics.OptionalGatherer`.
Simplifies metrics creation.
> Remove optional gatherer

- core/rawdb/accessors_state_sync.go
- core/state/snapshot/snapshot_test.go
make function comments match function names
> chore: make function comments match function names

- RELEASES.md
- plugin/evm/version.go
Bump version numbers in preparation for next release
CI
> prepare v0.13.6 release cycle

- go.mod
- go.sum
- peer/network_test.go
- plugin/evm/gossip.go
- scripts/versions.sh
Updates to https://github.com/ava-labs/avalanchego/pull/2753 version of the p2p API which adds a feature to respond with application-defined errors. This is needed as part of the interface update.
Updates interface signatures
CI
> Update to latest p2p API

- plugin/evm/vm.go
- plugin/evm/vm_test.go
The [specification for `GetBlockIDAtHeight`](https://github.com/ava-labs/avalanchego/blob/45a30f9868714d0afea39d3d948ec1dbbfadfc1c/snow/engine/snowman/block/vm.go#L52-L59) is:
```golang
// GetBlockIDAtHeight returns:
// - The ID of the block that was accepted with [height].
// - database.ErrNotFound if the [height] index is unknown.
//
// Note: A returned value of [database.ErrNotFound] typically means that the
//       underlying VM was state synced and does not have access to the
//       blockID at [height].
GetBlockIDAtHeight(ctx context.Context, height uint64) (ids.ID, error)
```
It should return `database.ErrNotFound` if the `height` index is unknown. Currently this function returns potentially arbitrary `blkID`s when queried for `height`s greater than the last accepted height.
1. …
> Fix VM.GetBlockIDAtHeight

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- scripts/actionlint.sh
Adds linter for github action configuration in keeping with a [similar addition to avalanchego](https://github.com/ava-labs/avalanchego/pull/3160).
> [ci] Add actionlint job

- go.mod
- go.sum
- plugin/evm/block.go
- plugin/evm/syncervm_client.go
- plugin/evm/syncervm_test.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- plugin/evm/vm_warp_test.go
- scripts/versions.sh
- warp/backend.go
- warp/backend_test.go
- warp/handlers/signature_request_test.go
- warp/warptest/block_client.go
This PR removes the usage of `block.Status()` from the `snowman.Block` interface.
The only actual code changes are:
1. In atomic tx verification
2. In warp block hash signing
> Remove block.Status

- plugin/evm/vm.go
This code is duplicated from avalanchego. We can call the AvalancheGo helper directly.
Calls `avax.GetAtomicUTXOs`
CI
> Use `avax.GetAtomicUTXOs`

- params/config_extra.go
- plugin/evm/vm.go
https://github.com/avalanche-foundation/ACPs/pull/131
Enables Cancun upgrade at the same time as the Avalanche "EUpgrade"
CI
> enables cancun at EUpgrade

- go.mod
- go.sum
- peer/network_test.go
- plugin/evm/syncervm_test.go
- plugin/evm/tx_gossip_test.go
- plugin/evm/vm_test.go
- plugin/evm/vm_warp_test.go
- precompile/contracts/warp/predicate_test.go
- scripts/versions.sh
- utils/snow.go
`avalanchego` was refactored and is already depending on one of the commits in this branch.
Magic 🧙 Also _Find and Replace_, but mostly magic.
Existing tests
> fix: use `avalanchego` new `*test` packages

- core/vm/jump_table.go
- eth/filters/filter_system_test.go
- metrics/sample.go
> chore: fix some function names

- plugin/evm/vm.go
Seems that local chains should be able to specify a chain config, without that being overwritten by `vm.Initialize()`
Corresponding avalanchego passing CI https://github.com/ava-labs/avalanchego/actions/runs/10292198882/job/28486105916?pr=3278
> Allow local chains to specify their own config

- go.mod
- go.sum
- params/config.go
- plugin/evm/vm.go
- scripts/versions.sh
AvalancheGo added upgrade config to snow context
Related AvalancheGo PR https://github.com/ava-labs/avalanchego/pull/3283
However we don't really need to change anything in Coreth since upgrades were written to chainConfig in genesis thus we have other source of information rather than upgrade configs in avalanchego/snow.Context. 
* uses network ID rather than chain ID in config selection
e2e should mostly cover this. I also did a local network testing with avalanchego to test out if network upgrades are passed correctly (but we don't actually use them)
> get upgrade configs from context

- go.mod
- go.sum
- internal/debug/flags.go
As per pull request https://github.com/ethereum/go-ethereum/pull/30253, memsize doesn't work on go 1.23
Coreth cannot work with Go 1.23 because of it breaks a dependency. The above pull request removes the dependency.
Removes some code that uses a dependency, as per the official ethereum change.
CI would hopefully pass.
> Remove memsize

- plugin/evm/gossiper_atomic_gossiping_test.go
- plugin/evm/mempool.go
- plugin/evm/mempool_atomic_gossiping_test.go
- plugin/evm/tx_gossip_test.go
- plugin/evm/vm_test.go
Inlines the call to `has` as it is only used in `Has`
Inlines the call
CI
> mempool: inline call to has

- core/vm/interpreter.go
This code is disabled and does not impact execution pre AP2 (tested on fuji, mainnet)
Deletes code
CI, reprocessing blocks from genesis to AP2
> remove pre-AP2 handling of genesis contract

- core/blockchain_test.go
- core/genesis_test.go
- core/state_processor_test.go
- internal/ethapi/api_test.go
- params/config.go
- params/config_extra.go
- plugin/evm/vm_test.go
- tests/init.go
Adds back BerlinBlock, LondonBlock, ShanghaiTime upgrades from upstream.
This is towards using more upstream packages and activating the desired behaviors via setting the Eth upgrade, instead of directly referencing the Avalanche upgrade names from predominantly upstream code.
This PR does not include modifying any of the Avalanche upgrade to the Eth upgrade, it only prepares the appropriate fields in the chain config.
In Avalanche AP2 & AP3 upgrades were enabled by timestamp however the corresponding Eth upgrade (Berlin, London) enable via block number. Since these upgrades already occurred, we can use their block numbers for canonical chains and use 0 in tests.
CI. (Note there is no behavioral changes for execution in this PR)
> params: add BerlinBlock, LondonBlock, ShanghaiTime

- core/genesis.go
- core/genesis_extra_test.go
- params/config.go
- params/config_extra.go
Current code does not function for mainnet/fuji.
When running a node with those chain IDs, the existing chain config will not have berlin/london & shanghai.
Therefore, we should apply the SetEthUpgrade anytime we unmarshal the config, including in the genesis,
prior to checking for compatibility.
As explained.
[x] Added UT
[x] Tested by using database from running node, then continuing with this version (fuji)
> fix: set eth upgrades in backwards compatible way

- params/config.go
- params/config_extra.go
- params/config_libevm.go
- params/hooks_libevm.go
- params/rules_extra.go
In lieu of comments on #662 re the `params` package. Let me know if the rationale behind anything isn't clear.
> Review of `params` package in #662

- scripts/build_test.sh
Fixes handling \r correctly in windows.
Already fixed in subnet-evm
> ci: fix windows flake test detection

- go.mod
- go.sum
- scripts/versions.sh
Bumps AvalancheGO to v1.11.13-rc.0 for the next release
> bump avago to v1.11.13-rc.0

- core/blockchain.go
- core/genesis.go
- core/genesis_test.go
- core/state/snapshot/generate_test.go
- core/state/statedb_fuzz_test.go
- core/state/statedb_test.go
- core/state/sync_test.go
- go.mod
- go.sum
- plugin/evm/atomic_trie.go
- plugin/evm/vm.go
- tests/state_test_util.go
- triedb/hashdb/database.go
- triedb/pathdb/database.go
This pull request includes several changes to the `triedb` package and its usage across different files to replace specific database configurations (`HashDB` and `PathDB`) with a more generalized `DBOverride` using `BackendConstructor`. Additionally, there are some dependency updates in the `go.mod` file.
> use DBOverride to specify backends

- core/state/statedb_multicoin_test.go
- core/types/state_account.go
- go.mod
- go.sum
- scripts/versions.sh
* Updated `github.com/ava-labs/avalanchego` and `github.com/ava-labs/libevm` to newer versions in `go.mod`.
* Modified `IsMultiCoin` function to use `SlimAccount` instead of `StateAccount` in `core/types/state_account.go`.
* Simplified the `TestGenerateMultiCoinAccounts` function by removing the RLP decoding step and directly checking the `IsMultiCoin` status in `core/state/statedb_multicoin_test.go`.
* Removed the unused `rlp` import from `core/state/statedb_multicoin_test.go`.
> use libevm v1.13.14-0.1.0.rc-2

- go.mod
- go.sum
- plugin/evm/vm_test.go
- plugin/evm/vm_warp_test.go
- precompile/contracts/warp/predicate_test.go
- precompile/contracts/warp/signature_verification_test.go
- scripts/versions.sh
- utils/snow.go
- warp/aggregator/aggregator_test.go
- warp/backend_test.go
- warp/handlers/signature_request_test.go
- warp/verifier_backend_test.go
This goes along with the following `avalanchego` PR:
https://github.com/ava-labs/avalanchego/pull/3576
See PR linked above
See PR linked above
See PR linked above
See PR linked above
> Encapsulate Signer

- RELEASES.md
- go.mod
- go.sum
- plugin/evm/version.go
- scripts/versions.sh
In correspondence to the avalanchego release.
> Release notes and avalanchego update

- RELEASES.md
- plugin/evm/version.go
Should start the release cycle so the rc's can be appropriately tagged when needed.
> prepare release cycle v0.14.1

- RELEASES.md
- ethclient/ethclient.go
- internal/ethapi/api.go
ANT (avalanche native tokens) precompiles have been disabled since v0.10.0, and there is no intention to re-enable them in the future.
We should remove these API calls to simplify the codebase.
Removes code
CI
docs PR https://github.com/ava-labs/avalanche-docs/pull/1979
done
> Remove eth_getAssetBalance API

- plugin/evm/vm.go
- plugin/evm/vm_test.go
Since Etna is active the code that adjusts the tx pool min base fee via a delayed timer is not needed anymore.
Simplifies the code.
CI
No
No
> Simplify txpool min base fee code (post etna cleanup)

- rpc/handler.go
- sync/statesync/state_syncer.go
- triedb/pathdb/database_test.go
> chore: fix function name in comment

- .github/workflows/ci.yml
- .github/workflows/sync-subnet-evm-branch.yml
So we use the Go version specified, not the latest one.
See https://github.com/actions/setup-go?tab=readme-ov-file#check-latest-version
Removed `check-latest: true` in Go setup action
CI passing
No
No
> chore(ci): remove `check-latest: true` to ensure the specified Go version is used

- triedb/pathdb/database_test.go
Fixes the flaky test generator
This pull request includes a change to the `generate` function in the `triedb/pathdb/database_test.go` file. The modification ensures that the `createAccountOp` operation is always selected for the first iteration, and a random operation is chosen for subsequent iterations.
* [`triedb/pathdb/database_test.go`](diffhunk://#diff-aa0965b61dc78a72ef175bc83cacadd7e5f29613ea543f86242a459b7259ccb9L231-R235): Modified the `generate` function to always select `createAccountOp` for the first iteration and randomize the operation for subsequent iterations.
It's fix to the test
No
No
> fix test generator

- params/avalanche_params.go
- plugin/evm/atomic/export_tx.go
- plugin/evm/atomic/import_tx.go
- plugin/evm/atomic/params.go
- plugin/evm/import_tx_test.go
- plugin/evm/imports_test.go
- plugin/evm/vm_test.go
The params package will trigger one-time libevm type registrations so we should not import them in the client / shared types packages with avalanchego/wallets.
>  avoid import of params from plugin/evm/atomic 

- metrics/prometheus/noop_register.go
- metrics/prometheus/prometheus.go
- plugin/evm/config/config.go
- plugin/evm/syncervm_test.go
- plugin/evm/vm.go
- plugin/evm/vm_test.go
>  suggestions for handling re-registration 

- core/evm.go
- core/state_transition.go
- core/vm/contracts_stateful_test.go
- core/vm/evm.go
- core/vm/instructions.go
- core/vm/runtime/env.go
- core/vm/runtime/runtime.go
- eth/tracers/api.go
- eth/tracers/internal/tracetest/calltrace_test.go
- eth/tracers/internal/tracetest/flat_calltrace_test.go
- eth/tracers/internal/tracetest/prestate_test.go
- eth/tracers/js/goja.go
- eth/tracers/native/4byte.go
- eth/tracers/native/call_flat.go
- eth/tracers/tracers_test.go
- internal/ethapi/api.go
- plugin/evm/prestate_tracer_test.go
- vm.BlockContext is an upstream type, let's put it back
- since the reason for the Timestamp() and Number() methods to implement a precompile interface (controlled by us), we can wrap the upstream type and have a Time() method.
(Or it can be put back to Timestamp())
> put back Time_ (use PrecompileBlockContext to wrap BlockContext) 

- plugin/evm/atomic/sync/atomic_block_sync_summary.go
- plugin/evm/atomic/sync/atomic_sync_extender.go
- plugin/evm/atomic/sync/atomic_sync_summary.go
- plugin/evm/atomic/sync/atomic_sync_summary_test.go
- plugin/evm/atomic/sync/atomic_syncer_test.go
- plugin/evm/message/block_request.go
- plugin/evm/message/block_request_test.go
- plugin/evm/message/block_sync_summary.go
- plugin/evm/message/block_sync_summary_test.go
- plugin/evm/message/code_request_test.go
- plugin/evm/message/codec.go
- plugin/evm/message/leafs_request_test.go
- plugin/evm/message/signature_request_test.go
- plugin/evm/message/syncable.go
- plugin/evm/sync/syncervm_client.go
- plugin/evm/vm.go
- plugin/evm/vm_warp_test.go
- sync/client/client_test.go
- sync/handlers/block_request_test.go
- sync/handlers/code_request_test.go
- sync/handlers/leafs_request_test.go
- sync/statesync/code_syncer_test.go
- sync/statesync/sync_test.go
- warp/aggregator/signature_getter.go
- warp/handlers/signature_request_test.go
- warp/service.go
Replaces error-prone sync summary type registration with a initializer that returns codec. 
* [`plugin/evm/message/block_sync_summary.go`](diffhunk://#diff-70b983c16384cd2dee3cb153acd3db9c0ce37934c77cd39809fcd2ac39b40490R1-R123): Introduced a new codec manager `codecWithBlockSync` for `BlockSyncSummary` and moved related code from `syncable.go` to here.
* [`plugin/evm/message/codec.go`](diffhunk://#diff-295ec2bc5b901db96bc911c27f3ef2df3eaf51e592081cab92d1dd51cbe372bcL18-R30): Added a `NewCodec` function to create codec managers for different sync summary types, replacing the previous global `Codec` variable. [[1]](diffhunk://#diff-295ec2bc5b901db96bc911c27f3ef2df3eaf51e592081cab92d1dd51cbe372bcL18-R30) [[2]](diffhunk://#diff-295ec2bc5b901db96bc911c27f3ef2df3eaf51e592081cab92d1dd51cbe372bcL …
> create new codec with correct type

- core/state/snapshot/snapshot.go
- core/state/statedb.go
- eth/gasprice/feehistory.go
- rpc/http.go
Applies various fixes from recent changes to upstream code to the coreth codebase
> Apply upstream fixes (up to d3cc618)

- plugin/evm/gossip.go
- plugin/evm/validators.go
- plugin/evm/vm.go
Avoids a panic if the node is not configured correctly.
> fix panic if config duration is set to 0

- consensus/dummy/dynamic_fees.go
- params/avalanche_params.go
1. `rollupWindow` is currently defined twice and `1 > 2` 😉.
2. The relationship between `DynamicFeeExtraDataSize` and `RollupWindow` is clarified.
- Doesn't introduce any new dependencies on the `params` package.
- Is a pure refactor.
CI
No.
No.
> Reduce magic numbers in dynamic fees

- consensus/dummy/dynamic_fee_window.go
- consensus/dummy/dynamic_fee_window_test.go
- consensus/dummy/dynamic_fees.go
- consensus/dummy/dynamic_fees_test.go
- params/avalanche_params.go
The existing windowing logic is overly complex.
1. The format of the window is baked into `CalcBaseFee`.
2. The implementation supports arbitrary sized window elements even though we never use this. Specifically how we have `rollWindow` and `rollLongWindow` even though all we ever use are `uint64`s.
Moves all the windower logic into a new type `DynamicFeeWindow`
Expanded unit tests (and existing dynamic fees tests)
no.
no.
> Cleanup dynamic fee windower logic

- core/state_processor.go
- core/state_processor_ext.go
Similar to https://github.com/ava-labs/subnet-evm/pull/1442
- Move our code from state_processor.go to state_processor_ext.go
- Slight modifications to state_processor.go to make it more alike geth master
> chore(core): split our code from state_processor.go in state_processor_ext.go

- core/genesis.go
- core/state_processor.go
- core/state_processor_ext.go
- core/types/block.go
- eth/state_accessor.go
- eth/tracers/api.go
- eth/tracers/api_test.go
- miner/worker.go
- plugin/evm/block.go
In `core/types`, the `Block` method `Timestamp` does the same as the method `Time` and **is not present upstream** (this causes small difficulties in #750)
- Define `core.BlockContext` implementing `contract.ConfigurationBlockContext` (same as subnet-evm)
- Use `core.NewBlockContext` to convert `types.Block` and `types.Header` for calls to `core.ApplyUpgrades`
Existing CI passing
No
No
> chore(core/types): remove `Blocks`'s `Timestamp()` method

- plugin/evm/atomic_trie.go
- plugin/evm/atomic_trie_test.go
- Removes the atomic trie dependency on the `core` package
- Unneeded use of a 1-length bounded buffer
1. Add (deep) unit test for `atomicTrie.AcceptTrie`
- Tests all happy code paths
- Tests derefencing occurs by inserting a dirty node and checking the storage size goes back to zero
2. Remove `tipBuffer` field, and use the existing `lastAcceptedRoot` field with a direct call to `a.trieDB.Dereference` on the previous root.
`Test_atomicTrie_AcceptTrie` with commit 1, 2 and 3.
No
No
> chore(plugin/evm): remove `core.BoundedBuffer` from `atomicTrie`

- plugin/evm/atomic/vm/block_extension.go
- plugin/evm/block.go
- plugin/evm/block_manager.go
- plugin/evm/extension/config.go
- plugin/evm/vm.go
- plugin/evm/vm_extensible.go
- plugin/evm/vm_test.go
Seems we can inline the 2 fields of the blockManager to the block itself.
This is 1 less "manager" abstraction to maintain and understand. I didn't like this abstraction as I'm not sure what it represents. This link has a good writeup which I agree with https://softwareengineering.stackexchange.com/a/112444/144520
Previously the block already had access to the vm pointer, so it seems fine to add another pointer. It may be possible to simplify this a bit more (perhaps putting the responsibility of processing block hooks back on the VM or entirely wrapping the block type, which I can explore next), but I think this is a good start.
We can subsequently rename block_manager.go or re-distribute the methods of that file.
> simplify: remove blockManager type

- consensus/dummy/dynamic_fees.go
- core/txpool/blobpool/blobpool.go
- core/txpool/legacypool/legacypool.go
- eth/gasprice/gasprice.go
- plugin/evm/vm.go
This return value is never used (and with the ACP-176 work, `CalcBaseFee` won't return the extra field).
no.
no.
> Remove `header.Extra` from `EstimateNextBaseFee`

- consensus/dummy/consensus.go
- consensus/dummy/dynamic_fees.go
- utils/numbers.go
- utils/numbers_test.go
Cleans up `verifyHeaderGasFields` a bit.
Ensures that `CalcBaseFee` returns reasonable values (BaseFee < 2^256). This is technically a breaking change... But this can't actually be hit on fuji or mainnet (as the maximum amount of AVAX that can exist wouldn't be sufficient to produce fees so large).
Adds a `BigEqual` helper that supports `nil` values.
Added unit tests + CI
No.
No.
> Cleanup header gas verification

- go.mod
- go.sum
- scripts/versions.sh
Fixes CI since the branch avalanchego was bumped to previously is now merged and we can depend on master instead
> ci: bump avalanchego to master

- consensus/dummy/dynamic_fees.go
- consensus/dummy/dynamic_fees_test.go
- params/avalanche_params.go
In 7ab07dc0f59b6f3826f5021bd0548c9716b049f2 `params.BaseFeeChangeDenominator` was incorrectly renamed to `params.ApricotPhase4BaseFeeChangeDenominator`.
in c2fde6191604c3d6bea0035012ffb0287c6e4f3b `params.BaseFeeChangeDenominator` was finalized for AP3, not AP4.
Rename
N/A
No
No
> Fix `params.ApricotPhase4BaseFeeChangeDenominator` name

- consensus/dummy/dynamic_fees.go
- consensus/dummy/dynamic_fees_test.go
- params/avalanche_params.go
- plugin/evm/ap4/cost.go
This is the start of removing the usage of the `params` package to stuff all configurations.
Is PR moves and documents parameters that were defined for the AP4 upgrade in the AP4 package.
Move + comment
CI
No
No
> Move AP4 params

- go.mod
- go.sum
- plugin/evm/vm_warp_test.go
- precompile/contracts/warp/predicate_test.go
- precompile/contracts/warp/signature_verification_test.go
- scripts/versions.sh
- warp/aggregator/aggregator_test.go
Use fallible bls.Signer api
The `bls.Signer` api is changing
> Update avalanchego version

- eth/api_backend.go
- eth/gasprice/gasprice_test.go
- params/denomination.go
- plugin/evm/ap3/window.go
- plugin/evm/ap4/cost.go
- plugin/evm/export_tx_test.go
- plugin/evm/gossip_test.go
- plugin/evm/header/base_fee.go
- plugin/evm/header/base_fee_test.go
- plugin/evm/header/block_gas_cost.go
- plugin/evm/header/block_gas_cost_test.go
- plugin/evm/header/dynamic_fee_windower.go
- plugin/evm/header/extra_test.go
- plugin/evm/import_tx_test.go
- plugin/evm/tx_test.go
- plugin/evm/vm_test.go
- plugin/evm/vm_warp_test.go
- utils/denomination.go
This PR primarily cleans up the tests in the `plugin/evm/header` package.
Additionally, it slightly cleans up the `MinRequiredTip` function and renames it to `EstimateRequiredTip` to align with the `EstimateNextBaseFee` function.
1. Add tests
2. Rename
CI
No.
No.
> Improve `plugin/evm/header` tests

- core/types/imports.go
- core/types/libevm.go
- core/types/state_account.go
- Sort alphabetically libevm imports in `imports.go`
- Move `state_account.go`'s libevm imports to `imports.go`
- Move extras registration from `state_account.go` to new file `libevm.go`
> chore(core/types): code restructure to accomodate future libevm changes

- consensus/dummy/consensus.go
- core/chain_makers.go
- core/state_processor_test.go
- miner/worker.go
ACP-176 changes the `ExtraPrefix` to be dependent on the `GasUsed` and `ExtDataGasUsed`, in the block. Which is only available after building it. This PR moves the generation of the `ExtraPrefix` to live inside of `FinalizeAndAssemble` rather than at the initial header creation.
Moves code around.
Existing CI.
No.
No.
> Move `header.ExtraPrefix` calculation

- consensus/dummy/consensus.go
- core/chain_makers.go
- miner/worker.go
- plugin/evm/block_verification.go
- plugin/evm/header/gas_limit.go
- plugin/evm/header/gas_limit_test.go
1. Currently `header.GasLimit` is verified in multiple places (with duplicate code). This centralizes the verification in a single location.
2. Currently `header.GasLimit` is calculated in multiple places (with duplicate code). This centralizes the generation in a single location.
3. Adds tests for `GasLimit` calculations and verifications
This PR utilizes the observation that `core.CalcGasLimit` is an optional block building rule, and is not required to be utilized. This PR changes the block building logic for pre-AP1 code to build blocks with the same gas limit as its parent (rather than moving toward the `ap1.GasLimit`.
Added unit tests + CI
No.
No.
> Move `GasLimit` handling into the `header` package

- core/evm.go
- core/vm/evm.go
- plugin/evm/block.go
- plugin/evm/header/extra.go
- plugin/evm/header/extra_test.go
- plugin/evm/vm_warp_test.go
- predicate/predicate_bytes.go
- predicate/predicate_bytes_test.go
ACP-176 changes the parsing of the `header.Extra` field, so any parsing of the field now requires access to the chain rules.
Moves the parsing of the `header.Extra` field into the `NewEVM` function so that the chain rules are available. 
CI
No.
No.
> Move predicate header parsing

- .github/workflows/ci.yml
- .github/workflows/sync-subnet-evm-branch.yml
Removes static versions and uses version from go.mod. 
Thanks @qdm12 for showing that.
uses `go-version-file` option for `setup-go` action
CI
No
No
> chore(ci): use go.mod Go version for actions/setup-go

- core/types/block.go
- core/types/header_ext.go
- core/types/header_ext_test.go
- core/types/imports.go
- Implement `PostCopy` header hook
- Remove `CopyHeader` and use imported one from libevm
➡️  [header copy hooks libevm PR](https://github.com/ava-labs/libevm/pull/106/files)
> chore(core/types): `Header` libevm `PostCopy` hook (5)

- consensus/dummy/consensus.go
- core/test_blockchain.go
1. With ACP-176 the base fee changes, so the required gas cost changes. Rather than updating the string matches, this uses more standard error checking.
2. WithACP-176 the block capacity is only increased with the passage of time, so the gap between blocks is changed from 0 to 1 so that transactions can be issued correctly.
- Returns a standard error for insufficient block gas
- Updates tests
CI
No.
No.
> Cleanup block fee tests

- plugin/evm/block_verification.go
- plugin/evm/vm.go
This removes code that is not needed (and would complicate the introduction of ACP-176 if it were kept.
Replaces equality checks with existing helpers and removes unnecessary checks.
existing CI.
No.
No.
> Cleanup `SyntacticVerify`

- eth/gasprice/gasprice_test.go
- plugin/evm/header/block_gas_cost.go
- plugin/evm/header/block_gas_cost_test.go
1. `header.EstimateRequiredTip` currently assumes that the sum of the GasUsed and ExtraDataGasUsed is > 0. This adds a check so that the code can't panic if this invariant were to be broken.
2. `header.EstimateRequiredTip` currently rounds down, but we should actually round up.
Updates `header.EstimateRequiredTip`.
Added unit tests
No.
No.
> Round up in `header.EstimateRequiredTip`

- plugin/evm/upgrade/acp176/acp176.go
- plugin/evm/upgrade/acp176/acp176_test.go
1. Uses an existing constant
2. Exposes constants from the ACP-176 library to reduce the larger PR diff.
N/A
N/A
No.
No.
> Export ACP-176 constants

- eth/gasprice/fee_info_provider.go
- eth/gasprice/gasprice_test.go
Currently the gas price oracle doesn't account for extraDataGasUsed. This PR includes that gas and adds a unit test for it.
Sums the gas.
unit test
no.
no.
> Filter by total gas rather than GasUsed

- core/vm/evm.go
- plugin/evm/block.go
- plugin/evm/header/extra.go
- plugin/evm/header/extra_test.go
- plugin/evm/vm_warp_test.go
Factored out of #815 to make the libevm migration easier.
Passes rules (and doesn't use them yet) during predicate bytes parsing.
CI
No.
No.
> Add Rules to PredicateBytesFromExtra

- core/txpool/blobpool/blobpool_test.go
- plugin/evm/header/base_fee_test.go
- plugin/evm/header/dynamic_fee_windower.go
- plugin/evm/header/dynamic_fee_windower_test.go
- plugin/evm/header/extra.go
- plugin/evm/header/extra_test.go
- plugin/evm/upgrade/acp176/acp176.go
- plugin/evm/upgrade/acp176/acp176_test.go
- plugin/evm/upgrade/ap3/window.go
- plugin/evm/upgrade/ap3/window_test.go
This reduces the size of the `header` package by implementing the canonical serialization of both the ACP-176 fee state and the AP3 fee windower in their corresponding packages.
- Moves the AP3 windower code
- Implements the ACP-176 code
Added and existing unit tests
No.
No.
> Implement header.ExtraPrefix serialization in upgrades package

- core/rawdb/database.go
- go.mod
- Part of the core/rawdb migration to use libevm
- Using libevm `InspectDatabase`
- Define options passed to libevm `InspectDatabase`
> chore(core/rawdb): `InspectDatabase` uses libevm (8)

- consensus/dummy/consensus.go
- plugin/evm/header/block_gas_cost.go
- plugin/evm/header/block_gas_cost_test.go
moves AP4 gas limit calc to header (return nil)
BlockGasCost return type changed to big.Int (from uint64), and returns nil for !AP4 
added UT
no
no
> move ap4 block gas cost check to header

- scripts/versions.sh
Previously it was necessary to manually maintain the avalanchego version in versions.sh. Now the version is automatically detected via go modules.
- updates versions.sh to automatically determine the version/SHA from go module
- CI
- Manually checked the version used matched the go module version when invoking `bash -x scripts/build.sh`
N/A
N/A
> chore(scripts): automated avalanchego version detection if unset

- eth/gasprice/gasprice.go
See issue #858 
Rather than sampling base fees as well as tips, simply returns the next base fee in `SuggestPrice` and `EstimateBaseFee`. Additionally, removes sampling and tracking of gas fees from sampling method.
Existing unit tests
Yes, but unsure where
No
> fix(eth/gasprice): EstimateBaseFee using Next Fee

- accounts/abi/bind/bind_extra_test.go
I've added by mistake [a refactor commit](https://github.com/ava-labs/coreth/pull/851/commits/2773bbb7d6ee2616600085d473ff81de0330a825) (destined for #862) to already-approved #851 (yesterday evening in a rush, normal git push), and squashed merged it (overlooking that erroneous commit) this morning.
This reverses the changes such that these can be reviewed later in #862 where it should be. Kind of important to merge this so the changes for that test won't be associated with the rawdb commit, since it has nothing to do with it.
~I also suggest we require approvals on the last commit before merging, but keep the "no need to update branch" (as it is, at least for libevm), to keep it flexible whilst also preventing this kind of problem from happening again 😉~
Essentially reverts …
> chore(accounts/abi/bind): revert accidental changes to TestGetSenderNativeAssetCall

- accounts/abi/bind/bind_extra_test.go
- plugin/evm/rawdb/database_ext.go
Just a minor refactor for #791 but skipped to accelerate finishing the libevm branch (and not re-waiting for approvals, needing rebases for next branch etc.)
> refactor(core/rawdb): table-driven `InspectDatabase` config

- internal/ethapi/api.coreth.go
- internal/ethapi/api.coreth_test.go
On Fortuna activation, the `ethapi` uses Etna's min base fee. After ACP-176 is activated, the min base fee is lowered, resulting in an improper min application.
If the Fortuna timestamp is reached, will use `acp176.MinGasPrice` instead of `etna.MinBaseFee`.
Additional unit test checking the `chainCfg` in the eth backend.
No
Unsure
> fix(internal/ethapi): fix minBaseFee for fortuna

- core/types/block_test.go
- scripts/eth-allowed-packages.txt
Until a complete transition to a `libevm` package, it shouldn't be allowed to be imported directly.
Remove the package from the allowed list and move a `types` test into `package types_test` to avoid a circular dependency.
NA
No
No
> chore: disallow direct `libevm/params` import

- accounts/abi/bind/util_test.go
Tiny PR changing code that was [meant to be changed in the master branch](https://github.com/ava-labs/coreth/pull/669), instead of changing it in the libevm branch which feels a bit out of scope.
> chore(accounts/abi/bind): check errors from types.SignTx in util_test.go

- go.mod
- go.sum
- triedb/hashdb/database.go
- triedb/pathdb/database.go
- [Metrics were not enabled correctly](https://github.com/ava-labs/coreth/pull/880)
- Address comments on the libevm branch review
- [BackendConstructor does not need to support a future Verkle tree option](https://github.com/ava-labs/coreth/pull/820#discussion_r2010194724)
- We want to [use upstream newTimestampCompatError which needs to be exported](https://github.com/ava-labs/coreth/pull/820#discussion_r2010136784)
- We want to use upstream rlpHash which needs to be exported
- We want to have a working rlpgen for type aliases
- [Metrics enabled corrrectly](https://github.com/ava-labs/libevm/commit/7be6bee7ab32ebb89cafa134d5f9c30b8c5df733)
- [Remove `config` argument from `BackendConstructor`](https://github.com/ava-labs/libevm/commit/87a2d57b9686fc406276d0c65ed046bc3149ff27) since it's …
> chore(deps): bump libevm to v1.13.14-0.2.0.rc.4

- .envrc
- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .gitignore
- README.md
- accounts/abi/bind/util_test.go
- core/genesis.go
- go.mod
- go.sum
- internal/ethapi/api.coreth.go
- internal/ethapi/api.coreth_test.go
- metrics/prometheus/enabled_test.go
- metrics/prometheus/prometheus_test.go
- scripts/dev_shell.sh
- scripts/known_flakes.txt
- scripts/tests.e2e.sh
- scripts/update_avalanchego_version.sh
This will, as before, need to be ff-only merged into libevm, from a terminal, once checks are passing on the PR.
> final merge master branch into libevm branch

- core/genesis_extra_test.go
Prior to this change, the unit test will still pass if the line:
```
params.SetEthUpgrades(storedcfg)
```
is removed from genesis.go.
This is because `RewindToBlock` and `RewindToTime` are overloaded where 0 both means "rewind to genesis" and that "block number or timestamp is not used for setting the fork" (i.e, the other one is used).
If the line is removed it will conflict on the DAO fork block / flag, then rewind to genesis, then the UT will pass, which defeats the purpose of this UT.
> test(core/genesis): fix UT to be sensitive to `SetEthUpgrades`

- metrics/prometheus/prometheus.go
- metrics/prometheus/prometheus_test.go
Case was missing in switch making all metrics registration error out.
add a case to handle StandardGaugeInfo
> fix(metrics/prometheus): add case for `StandardGaugeInfo` to skip

- go.mod
- go.sum
> chore: update libevm to v1.13.14-0.2.0.release

- scripts/build_firewood.sh
- Added check_prerequisites to verify that cargo and git are on the path before starting
- Sanity checked the firewood repo (must contain Cargo.toml)
- If the repo existed and contains changes, don't clobber them
- Correctly handle failures from build_firewood and install_firewood
- Quote pwd return values in case they contain something nasty like spaces
- use pushd and popd instead of saving off the directory
- Reports errors earlier than letting commands fail
- Makes sure the firewood repo is sane before starting
- Doesn't clobber lost work
- If one step fails, we should fail instead of continuing
- pwd could contain something bad, this handles that case
- pushd and popd are more ergonomic
Self-explanatory
Ran PATH=/bin scripts/build_firewood.sh which fails because it can't find git or …
> build_firewood shell script improvements

- RELEASES.md
- internal/ethapi/api.coreth.go
- internal/ethapi/api.coreth_test.go
- plugin/evm/config/config.go
- plugin/evm/vm.go
1. Fortuna has been activated, so the `.IsFortuna` check is no longer needed.
2. Previously, the base fee was set between [80%, 120%] of the chain values (with min and max values enforced). Post activation of Fortuna, the price has been extremely stable. This means that issuing a transaction at 80% of the base fee is all but guaranteed not to be included on chain. The base fee is now always set at 200% of the chain base fee.
- Cleans up code that isn't needed.
- The base fee is not the fee that is actually paid by the end user, so it is safe to over-estimate.
I don't think the configs that are being changed are documented anywhere... But if they are, they should be updated.
Done.
> Simplify `eth_suggestPriceOptions` handling of `baseFee`s

- plugin/evm/vm.go
This PR removes deadcode from the Coreth VM that's left over from old VM interfaces.
Deletes unused code.
Existing test coverage.
No
No
> Remove deadcode from old vm interfaces

- .github/workflows/ci.yml
- go.mod
- go.sum
- plugin/evm/atomic/mempool.go
- plugin/evm/export_tx_test.go
- plugin/evm/tx_test.go
- plugin/evm/vm.go
- warp/backend.go
- warp/backend_test.go
- warp/handlers/signature_request_test.go
- warp/verifier_backend_test.go
This pull request introduces several updates to improve the codebase by replacing the custom LRU cache implementation with a more streamlined `lru.Cache` and refactoring the `secpCache` to use a pointer-based implementation. Additionally, it includes minor dependency updates and import optimizations.
* Replaced `cache.LRU` with `lru.Cache` across multiple files for better maintainability and consistency:
- Updated `discardedTxs` in `plugin/evm/atomic/mempool.go` to use `lru.NewCache` instead of `cache.LRU`. [[1]](diffhunk://#diff-c12ee7e53adb00b1d1cdf4206cfa5139bd1a3f2421a895addf7d0731403403c5L70-R70) [[2]](diffhunk://#diff-c12ee7e53adb00b1d1cdf4206cfa5139bd1a3f2421a895addf7d0731403403c5L101-R101)
- Refactored `warpSignatureCache` in `plugin/evm/vm.go` to use `lru.NewCache`.
- Updated …
> bump avalanchego to master (5381d56)

- plugin/evm/block.go
- plugin/evm/vm.go
The logger enables log structuring, but we have a couple sites that don't use it correctly.
Remove `fmt.Sprintf` from logs.
Ran locally and the logs look correct.
No.
No.
> Fix log structuring

- plugin/evm/block.go
Block verification currently reads imported UTXOs twice. Once in `verify`, and once in `onExtraStateChange`.
I was originally confused why this verification existed in `verify` at all, as it doesn't fully verify the UTXOs (the full verification is performed in `onExtraStateChange`). After looking back at the original introduction of the code to `verify`, the rationale made sense.
This PR improves the documentation in the current code so that we don't have to look back at old PRs to understand why this code is important.
Additionally, this aligns the behavior of `verifyUTXOsPresent` with `verifyPredicates`, so the bootstrapped check is only done once.
Just improving comments + making the code a bit more uniform.
CI
No.
No/
> Explain duplicated UTXO check

- README.md
- docs/releasing/README.md
Clarify when, and how to create a release.
↪️  [**Rendered readme**](https://github.com/ava-labs/coreth/blob/qdm12/docs/releasing/docs/releasing/README.md)
Will be tested on next release v0.15.0. Maybe we should merge this post-v0.15.0 to make it contain everything.
Yes, linked from root README.md
> docs: add releasing document

- .github/workflows/ci.yml
- go.mod
- go.sum
- plugin/evm/syncervm_test.go
- plugin/evm/vm_test.go
- plugin/evm/vm_warp_test.go
Fixes e2e tests that failing because the dependent commit does not exist anymore on avalanchego repo.
bumps avalanchego to commit in https://github.com/ava-labs/avalanchego/pull/3977
e2e
no
no
> fix AvalancheGo version and nil configs for Granite

- miner/worker.go
- plugin/evm/vm_test.go
This PR updates the block building logic to return an error if the available gas capacity would be < min(80% of GasLimit, 15m).
This ensures that when the chain is quickly increasing fees due to all gas being consumed, block building will pause to allow the capacity to refill until it can guarantee that there is space for a transaction with a gas limit of at least 80% of the gas limit (currently configured on mainnet to 16m implying transactions of size 12.8M gas can be included).
The original heuristic was to ONLY check that at least 80% of the gas limit is available, but as the gas target scales up this would trade off delaying block production to guarantee greater than 15m gas is available. This check is added to ensure that transactions that could be included prior to ACP-176 can …
> Require min available capacity to build a block

- .github/workflows/ci.yml
- go.mod
- go.sum
Firewood PR #959 requires an updated libevm branch to build.
Since ava-labs/libevm#187, libevm's main branch can be used in `go.mod` files with the cherry-picked commits. Uses ava-labs/avalanchego#4006
CI
No
No?
> chore: Update libevm

- core/blockchain.go
- core/state/snapshot/snapshot.go
- core/state/statedb_multicoin_test.go
- go.mod
- go.sum
- params/hooks_libevm.go
- triedb/hashdb/database.go
- triedb/pathdb/database.go
Uses the most recent `libevm` update.
There were two additional changes required to update hooks and options correctly.
Unit tests
No
No
> build: Update `libevm` to `v1.13.14-0.3.0.rc.1`

- plugin/evm/atomic/sync/extender.go
- plugin/evm/atomic/sync/leaf_handler.go
- plugin/evm/atomic/sync/summary_provider.go
- plugin/evm/atomic/vm/vm.go
There were few reviews in https://github.com/ava-labs/coreth/pull/1009 after it was merged. This PR intends to responde those.
This pull request refactors the atomic sync components in the EVM plugin to improve clarity and maintainability. Key changes include renaming internal types to exported ones, enhancing comments for better documentation, and updating initialization logic to align with the new architecture.
* [`plugin/evm/atomic/sync/extender.go`](diffhunk://#diff-aebac339a2d897f6e91947de63526b1fee94fbf080a087cc70d0b83ed8336677L19-R36): Renamed `extender` to `Extender` and updated comments to clarify its role as the sync extender for the atomic VM. Updated methods to align with the new exported type. [[1]](diffhunk://#diff-aebac339a2d897f6e91947de63526b1fee94fbf080a087cc70d0b83ed8336 …
> use explicity structs and innervm calls

- plugin/evm/api.go
- plugin/evm/atomic/txpool/mempool.go
- plugin/evm/atomic/txpool/mempool_test.go
- plugin/evm/atomic/vm/block_extension.go
- plugin/evm/atomic/vm/vm.go
- plugin/evm/block_builder.go
- plugin/evm/config/constants.go
- plugin/evm/eth_gossiper.go
- plugin/evm/export_tx_test.go
- plugin/evm/extension/config.go
- plugin/evm/gossip/handler.go
- plugin/evm/gossiper_atomic_gossiping_test.go
- plugin/evm/mempool_atomic_gossiping_test.go
- plugin/evm/syncervm_test.go
- plugin/evm/tx_gossip_test.go
- plugin/evm/tx_test.go
- plugin/evm/vm.go
- plugin/evm/vm_extensible.go
- plugin/evm/vm_test.go
- plugin/evm/vmerrors/errors.go
Moves atomic mempool and gossip handler to atomic vm
This pull request introduces significant changes to the `plugin/evm` module, focusing on refactoring the `Mempool` implementation, improving atomic transaction handling, and enhancing gossip protocols for atomic transactions. The most important changes include replacing the `NewMempool` constructor with an `Initialize` method, updating `Mempool` usage across the codebase, introducing gossip handlers for atomic transactions, and restructuring the VM initialization process.
* Replaced the `NewMempool` constructor with an `Initialize` method for better flexibility in instantiation. Updated all instances of `NewMempool` to use the new `Initialize` method. (`plugin/evm/atomic/txpool/mempool.go`, `plugin/evm/atomic/txpool/mempool_test.go`) …
> move mempool and gossip handlers to atomic vm

- RELEASES.md
- eth/filters/api.go
- eth/filters/api_test.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
Cherry picks https://github.com/ethereum/go-ethereum/pull/31876:
The address filter was never checked against a maximum limit, which can be somewhat abusive for API nodes. This PR adds a limit similar to topics
This pull request introduces a new validation to enforce a maximum limit on the number of addresses allowed in filter criteria for Ethereum logs. It includes updates to the `FilterAPI` and `EventSystem` logic, as well as corresponding test cases to ensure the new constraint is properly enforced.
* **Validation for maximum addresses in filter criteria**:
- Added a new constant, `maxAddresses`, set to 100, to define the maximum allowable addresses in a filter.
- Introduced a new error, `errExceedMaxAddresses`, to handle cases where the number of addresses exceeds the limit.
- Updated …
> eth/filters: add address limit to filters (#31876)

- core/blockchain.go
Accounts for missing piece of block insertion metrics: signature recovery.
Adds a counter for signature recovery time.
n/a
No need to be documented in this PR since corresponding metrics are not documented.
No
> Add block signature recovery timer

- .github/workflows/ci.yml
- go.mod
- go.sum
- plugin/evm/vm.go
Needed to support header-based routing, see https://github.com/ava-labs/avalanchego/pull/4036
See https://github.com/ava-labs/avalanchego/pull/4036
See https://github.com/ava-labs/avalanchego/pull/4036
No
Yes, this is an avalanchego version bump
> Update interface to the latest version of avalanchego

- RELEASES.md
- core/blockchain.go
- core/blockchain_ext_test.go
- core/blockchain_repair_test.go
- core/blockchain_test.go
- core/genesis.go
- core/genesis_test.go
- core/state_manager.go
- eth/backend.go
- eth/state_accessor.go
- eth/tracers/api_test.go
- eth/tracers/tracers_test.go
- plugin/evm/config/config.go
- plugin/evm/config/config.md
- plugin/evm/vm.go
- plugin/evm/vm_test.go
- plugin/evm/vm_warp_test.go
- tests/state_test_util.go
This is the final step to completely enable Firewood to bootstrap in the EVM.
- Debug APIS and Snapshot (requires an iterator)
- Integrating firewood metrics/logging - [see this comment](https://github.com/ava-labs/coreth/pull/959#discussion_r2143268672)
- E2E testing
- State Sync
- Performance testing to find optimizations/weak points
This hooks into existing libevm functionality as necessary.
Unit tests, bootstrap mainnet.
Yes.
Yes.
> feat: enable blockchain ops and tests

- RELEASES.md
- plugin/evm/config/config.md
- plugin/evm/vm.go
- plugin/evm/vm_test.go
Metrics inside Firewood's code are not yet tracked. This enables them.
Firewood implemented a `Gatherer` that can be scraped by prometheus on the global metrics recorder in Rust via FFI.
Tested locally using `tmpnet`.
Yes.
Yes.
> feat: Firewood metrics

- Taskfile.yml
Adds an option to running the update avalanchego script, to help coders identify any failures in CI.
> ci: Add line display for avalanchego version script

- go.mod
- metrics/prometheus/prometheus.go
- metrics/prometheus/prometheus_test.go
1. When I run the `TestGatherer_Gather` test locally, it fails consistently with:
```
--- FAIL: TestGatherer_Gather (0.00s)
/Users/stephen/go/src/github.com/ava-labs/coreth/metrics/prometheus/prometheus_test.go:90: 
Error Trace:	/Users/stephen/go/src/github.com/ava-labs/coreth/metrics/prometheus/prometheus_test.go:90
Error:      	Not equal: 
expected: []string{"name:\"test_counter\" type:COUNTER metric:{counter:{value:12345}}", "name:\"test_counter_float64\" type:COUNTER metric:{counter:{value:1.1}}", "name:\"test_gauge\" type:GAUGE metric:{gauge:{value:23456}}", "name:\"test_gauge_float64\" type:GAUGE metric:{gauge:{value:34567.89}}", "name:\"test_histogram\" type:SUMMARY metric:{summary:{sample_count:0 sample_sum:0 quantile:{quantile:0.5 value:0} quantile:{quantile:0.75 value:0} …
```
> Fix summary metrics + flaky test

- plugin/evm/atomic/export_tx.go
Avalanchego hasn't removed these just because coreth still uses them.
> `Add64` and `Mul64` were replaced with `Add` and `Mul` respectively

- plugin/evm/vm.go
- sync/vm/client.go
There's a typo in `ClientConfig` naming.
Rename
UT 
No
No
> style: fix typo in sync client

- plugin/evm/atomic/txpool/mempool.go
- plugin/evm/atomic/txpool/mempool_test.go
- plugin/evm/atomic/txpool/metrics.go
- plugin/evm/atomic/txpool/txs.go
- plugin/evm/atomic/vm/vm.go
- plugin/evm/mempool_atomic_gossiping_test.go
- plugin/evm/vm_test.go
This is the first of (what may be a few) mempool cleanups. The goal of this PR is to avoid passing around uninitialized mempools.
Separates the mempool into two components. The first component `Txs` supports block building. The second component `Mempool` supports adding txs to the mempool.
- `Txs` does not depend on the `InnerVM`, yet implements everything required by the `InnerVM`. So it can be created prior to the `InnerVM` being initialized.
- `Mempool` is created after the `InnerVM` is initialized and has a reference to `Txs`.
Existing CI
No
No
> Refactor atomic mempool initialization

- RELEASES.md
- eth/api_debug.go
- internal/ethapi/api.go
- plugin/evm/config/config.md
Some of the eth APIs use `trie.StateTrie`, which is specific to geth's two-tier in-memory trie. These are not safe to be used with Firewood, since the intermediate nodes will not be found as expected. 
A long-term fix, if these APIs are necessary, would be to implement a Firewood-specific iterator in the FFI, and an easily-parsable proof method.
This just returns an error if Firewood is used for these nodes.
This is really hard to test. It can only occur in a production environment.
Yes.
Yes.
> fix: Ensure Firewood does not return data on unimplemented APIs

- core/state_transition.go
- go.mod
- go.sum
- params/hooks_libevm.go
Updates libevm to use additional eth updates and statedb refactor
Adds check from libevm interface change
UT
No.
No.
> chore: update libevm version to v1.13.14-0.3.0.rc.6

- .github/dependabot.yml
This changed dependabot to alert only for security updates
aligns avalanchego dependabot.yml file
Dependabot notifications?
No
No
> chore: change dependabot config

- plugin/evm/atomic/txpool/mempool.go
- plugin/evm/atomic/txpool/txs.go
Prior to the `WaitForEvent` refactor, this logic was required. However, now we are guaranteed that `PendingLen` will be called after `BuildBlock`. This means we never need to push a notification to the block builder while the block builder is handling a build block event.
Removes code that is no longer required.
Existing VM tests still pass.
No.
No.
> Simplify atomic mempool tx signaling

- consensus/misc/eip4844/eip4844_test.go
- log/handler.go
- log/logger.go
- scripts/upstream_files.txt
In a comment of #1117, it was pointed out that `upstream_files.txt` is missing several files, so this is corrected.
All files that also exist in `go-ethereum` should have the license header crediting them.
Lint test
No
No
> fix: license header file

- .avalanche-golangci.yml
- sync/statesync/trie_sync_tasks.go
This PR works towards completing https://github.com/ava-labs/coreth/issues/1144.
> style: enable nilerr linter 

- .avalanche-golangci.yml
- core/blockchain_ext_test.go
- core/extstate/database_test.go
- params/config_extra.go
- plugin/evm/atomic/vm/block_extension.go
- plugin/evm/atomic/vm/import_tx_test.go
- plugin/evm/atomic/vm/tx_test.go
- plugin/evm/customrawdb/accessors_state_sync_test.go
- plugin/evm/vm.go
- plugin/evm/vm_warp_test.go
- sync/handlers/leafs_request_test.go
- triedb/firewood/database.go
- warp/backend_test.go
- warp/service.go
- warp/verifier_backend_test.go
This PR works towards completing https://github.com/ava-labs/coreth/issues/1144.
> style: enable gocritic linter

- plugin/evm/customheader/block_gas_cost.go
- plugin/evm/customheader/block_gas_cost_test.go
We don't need to verify the block fee if the block gas cost is 0
skips verify block fee if block gas cost is 0
added test
No
No
> skip verify block fee if is 0

- consensus/dummy/consensus.go
- ethclient/simulated/backend.go
- plugin/evm/customheader/time.go
- plugin/evm/customheader/time_test.go
- plugin/evm/vm.go
- plugin/evm/wrapped_block.go
It's more sensible to do all time verification for block headers in a single location for ACP-226, since it is spread currently between `semanticVerify` and `eng.VerifyHeader`, which is unnecessary. One fun side effect is that we no longer need to provide a clock to the consensus callback engine.
Closes #1211
Moves a check from consensus callbacks
Existing UT, added one
No.
No.
> refactor: move header time verification

- plugin/evm/wrapped_block.go
In a prior PR review it was suggested that verification code be moved `semanticVerify`. This closes #1221 
Existing UT 
No
No
> Move verification code to `semanticVerify`

- miner/worker.go
The time adjustment only checks the parent time in seconds, but it should also check the parent time in milliseconds
adds the wall clock <> parent milliseconds check
no test (will be added with a upcoming refactor)
no
no
> check the parent.TimeMilliSeconds in wall clock adjustment

- eth/tracers/api.go
- eth/tracers/api_test.go
Addresses ethereum/go-ethereum#32175 in which the `BLOCKHASH` op code returns `0x00` when simulating a transaction at block `HEAD+1`.
Sets the parent block hash based on code from ethereum/go-ethereum#32183. A cherry-pick wasn't viable due to conflicts.
UT from the above PR, which failed before adding the fix.
Yes
Yes
> fix: block hash when overriding to block n+1

- precompile/contracts/warp/predicate_test.go
As part of ACP-181, we will be caching all validator sets at the current epoch height.
As part of this we will be changing the canonical representation of a validator set with a total weight that overflows uint64 to be the empty set rather than erroring during construction.
This adds an equivalence test to ensure this a not a breaking change.
Adds a test which verifies that the gas consumed is equal for both cases (and that both cases error).
It is a test
no
no
> Add warp test to verify equivalent gas consumed

- .github/workflows/ci.yml
- go.mod
- go.sum
We're currently using a commit from a branch, as a temporary workaround to the circular dependency.
Bump `avalanchego` version to latest on `master` (i.e. the merge commit of said branch).
Existing tests.
No
No
> build: use `avalanchego@master` instead of branch

- plugin/evm/vm.go
- warp/service.go
Currently `warp_getMessageAggregateSignature` and `warp_getBlockAggregateSignature` incorrectly override the `subnetID` twice.
Specifically, the intended behavior is:
- If the `subnetID` is not overridden, use this chain's validator set
- This is the "normal" case as this chain is sending the message.
- If the `subnetID` is overridden, use the validator set requested by the caller
- This allows the C-chain's APIs to be used to generate a signature for a subnet which is using their own validator set to verify the message.
This is almost what the logic does currently, but there is a weird edge case. If the `subnetID` is overridden to use the primary network's validator set and this chain has enabled the optimization to use the local validator set for the primary network, then the `subnetID` …
> Remove secondary validator override
